export const UPDATE_FILTER_OPTION = 'UPDATE_FILTER_OPTION';
export const REMOVE_SELECTED_OPTION = 'REMOVE_SELECTED_OPTION';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CLEAR_PRODUCT_LIST = 'CLEAR_PRODUCT_LIST';